### ISSUE TITLE
Missing json data in tutorial

### ISSUE THREAD

**Issue by dr-neptune** [renkun-ken/rlist#127]
Hi @renkun-ken

This package looks absolutely wonderful. I was hoping to go through the rlist tutorial (https://renkun-ken.github.io/rlist-tutorial/), but it seems that the links to the data used is broken.

Here is an example: 

people <- list.load("http://renkun.me/rlist-tutorial/data/sample.json")
friends <- list.load("http://renkun.me/rlist-tutorial/data/friends.json")

Is this data still available somewhere?

Thanks again for making this package!

**Comment by renkun-ken** [comment]
Thanks for reporting!

The link is broken due to the previous migration of my blog from GitHub Pages to Netlify.

Please use <https://renkun-ken.github.io/rlist-tutorial/data/sample.json> and <https://renkun-ken.github.io/rlist-tutorial/data/friends.json> instead.

I'll fix the links in the tutorial soon.

**Comment by renkun-ken** [comment]
Should be fixed now.
